create table people (id int not null auto_increment primary key, name varchar (25) not null, surname varchar (25) not null);
insert into people (name, surname) values ('Anatoliy', 'Omelchenko');
insert into people (name, surname) values ('Andrew', 'Parmon');
insert into people (name, surname) values ('Dmytro', 'Protsenko');
insert into people (name, surname) values ('Elena', 'Kolyshkina');
insert into people (name, surname) values ('Iana', 'Sitsinska');
insert into people (name, surname) values ('Igor', 'Shumeyko');
insert into people (name, surname) values ('Ilona', 'Bachynskaya');
insert into people (name, surname) values ('Julia', 'Cherchun');
insert into people (name, surname) values ('Julia', 'Shevchenko');
insert into people (name, surname) values ('Kateryna', 'Tretiak');
insert into people (name, surname) values ('Kateryna', 'Nemesh');
insert into people (name, surname) values ('Kateryna', 'Chorna');
insert into people (name, surname) values ('Kristina', 'Naumova');
insert into people (name, surname) values ('Maxim', 'Kriuchko');
insert into people (name, surname) values ('Maxim', 'Tsyvina');
insert into people (name, surname) values ('Natalia', 'Semidotska');
insert into people (name, surname) values ('Roman', 'Atamanchuk');
insert into people (name, surname) values ('Sofia', 'Kostiuchenko');
insert into people (name, surname) values ('Taras', 'Kazydub');
insert into people (name, surname) values ('Zhanna', 'Vasilevskaya');
select * from people;